# Generated by Django 4.2.9 on 2024-08-12 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vehicleManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_plate_number', models.CharField(max_length=16, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('makeyear', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('vehicle_type', models.CharField(choices=[('SE', 'Sedan'), ('SU', 'SUV'), ('MO', 'Motorcycle'), ('TR', 'Truck'), ('VA', 'Van'), ('BU', 'Bus'), ('OT', 'Other')], max_length=2)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('PE', 'Petrol'), ('DI', 'Diesel'), ('EL', 'Electric'), ('HY', 'Hybrid'), ('CN', 'CNG'), ('LP', 'LPG')], max_length=2)),
                ('transmission_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('S', 'Semi Automatic')], max_length=1)),
                ('maintenance_status', models.CharField(choices=[('A', 'Active'), ('I', 'In Maintenance'), ('O', 'Out of Service'), ('R', 'Retired')], default='A', max_length=1)),
                ('registration_expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_id', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'staff_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', vehicleManagement.models.LocationField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleManagement.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('X', 'Cancelled'), ('R', 'Running'), ('D', 'Completed')], default='P', max_length=1)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_location', vehicleManagement.models.LocationField()),
                ('end_location', vehicleManagement.models.LocationField()),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'customer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleManagement.vehicle')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
