# Generated by Django 4.2.9 on 2024-08-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
        ('vehicleManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'staff_driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='userManagement.driver'),
        ),
    ]
